---
title: "HousingProject3"
author: "Ramesh Suragam"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading libraries
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(gridExtra)))
suppressMessages(suppressWarnings(library(MASS)))
```

### **Introduction:**

### **Loading Data:**
```{r}
#Loading the data
LondonData <- suppressMessages(suppressWarnings(read_csv("data/DataScienceProj.csv")))
head(LondonData)

#Checking for correlation
M <- cor(LondonData[,-1])
head(round(M,2))
library(corrplot)
corrplot(M, method="circle", order="hclust", sig.level = 0.01)
```

### **Data Cleanup:**
### Convert dummies to factors
```{r}
Dummy2Factor <- function(mat,lev1="Level1") {
      mat <- as.matrix(mat)
      factor((mat %*% (1:ncol(mat))) + 1,
          labels = c(lev1, colnames(mat)))
}

Age      <- Dummy2Factor(LondonData[,5:9],"PreWW1")
Type     <- Dummy2Factor(LondonData[,10:12],"Others")
Garage   <- Dummy2Factor(LondonData[,13:14],"HardStnd")
Bedrooms <- Dummy2Factor(LondonData[,18:21],"BedOne")

MyData <- data.frame(LondonData[,c(2:4,15:17,22,23,26)],Age,Type,Garage,Bedrooms)
summary(MyData)

MyData$Tenfree <- factor(MyData$Tenfree)
MyData$CenHeat <- factor(MyData$CenHeat)
MyData$BathTwo <- factor(MyData$BathTwo)
MyData$NewPropD <- factor(MyData$NewPropD)

levels(MyData$Tenfree) <- c("no", "yes")
levels(MyData$CenHeat) <- c("no", "yes")
levels(MyData$BathTwo) <- c("no", "yes")
levels(MyData$NewPropD) <- c("no", "yes")

head(MyData)
```

### **Remove Outliers:**
```{r}
par(mfrow= c(2,2))
boxplot(MyData$Purprice)
MyData <- MyData[MyData$Purprice<600000,]

boxplot(Purprice~CenHeat,data=MyData)
boxplot(Purprice~BathTwo,data=MyData)
boxplot(Purprice~Age,data=MyData)
boxplot(Purprice~Type,data=MyData)
boxplot(Purprice~Garage,data=MyData)
boxplot(Purprice~Bedrooms,data=MyData)
par(mfrow= c(1,1))
```
### **Exploratory Analysis:**
### **Checking for price:**
```{r}
p1 <- ggplot(MyData, aes(x=Purprice)) + geom_histogram(bins = 100, color="black", fill="white")+
  geom_vline(aes(xintercept=mean(Purprice)),
            color="blue", linetype="dashed", size=1)

p2 <- ggplot(MyData, aes(x=Purprice)) + 
 geom_histogram(bins = 100, aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")

p3 <- ggplot(MyData, aes(x=log(Purprice))) + 
 geom_histogram(bins = 100, aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")



grid.arrange(p1, p2, p3, nrow=3)
```

```{r}
p4 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$CenHeat)) +
  geom_histogram(bins = 50, fill= "white", alpha=0.5, position="identity")+
  theme(legend.position = "top")

p5 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$CenHeat)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p6 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$Tenfree)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p7 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$NewPropD)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p8 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$Age)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p9 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$Type)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p10 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$Garage)) +
  geom_freqpoly()+
  theme(legend.position = "top")

p11 <- ggplot(MyData, aes(x=log(Purprice), color=MyData$Bedrooms)) +
  geom_freqpoly()+
  theme(legend.position = "top")

grid.arrange(p4, p5, nrow=2)
grid.arrange(p6, p7, nrow=2)
grid.arrange(p8, p9, nrow=2)
grid.arrange(p10, p11, nrow=2)
```

```{r}
ld_model <- lm(Purprice~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = MyData)
step <- stepAIC(ld_model, direction="both")
step$anova
```

```{r}
library(leaps)

set.seed(123)
sample <- sample(c(TRUE, FALSE), nrow(MyData), replace = T, prob = c(0.6,0.4))
train <- MyData[sample, ]
test <- MyData[!sample, ]

ld_model <- regsubsets(Purprice~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = train,nvmax = 10)
results <- summary(ld_model)
plot(ld_model,scale="adjr2")

# extract and plot results
tibble(predictors = 1:10,
       adj_R2 = results$adjr2,
       Cp = results$cp,
       BIC = results$bic) %>%
  gather(statistic, value, -predictors) %>%
  ggplot(aes(predictors, value, color = statistic)) +
  geom_line(show.legend = F) +
  geom_point(show.legend = F) +
  facet_wrap(~ statistic, scales = "free")

which.max(results$adjr2)
which.min(results$bic)
which.min(results$cp)

ld_frwd <- regsubsets(Purprice~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = train, method = "forward",nvmax = 10)
results <- summary(ld_frwd)
plot(ld_frwd,scale="adjr2")

# extract and plot results
tibble(predictors = 1:10,
       adj_R2 = results$adjr2,
       Cp = results$cp,
       BIC = results$bic) %>%
  gather(statistic, value, -predictors) %>%
  ggplot(aes(predictors, value, color = statistic)) +
  geom_line(show.legend = F) +
  geom_point(show.legend = F) +
  facet_wrap(~ statistic, scales = "free")

which.min(results$cp)

ld_bkwd <- regsubsets(Purprice~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = train, method = "backward",nvmax = 10)
results <- summary(ld_bkwd)
plot(ld_bkwd,scale="adjr2")

# extract and plot results
tibble(predictors = 1:10,
       adj_R2 = results$adjr2,
       Cp = results$cp,
       BIC = results$bic) %>%
  gather(statistic, value, -predictors) %>%
  ggplot(aes(predictors, value, color = statistic)) +
  geom_line(show.legend = F) +
  geom_point(show.legend = F) +
  facet_wrap(~ statistic, scales = "free")

which.min(results$cp)

coef(ld_model,10)
coef(ld_frwd,10)
coef(ld_bkwd,10)

test_m <- model.matrix(Purprice ~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = test)

validation_errors <- vector("double", length = 10)

for(i in 1:10) {
  coef_x <- coef(ld_model, id = i)                     # extract coefficients for model size i
  pred_x <- test_m[ , names(coef_x)] %*% coef_x           # predict salary using matrix algebra
  validation_errors[i] <- mean((test$Purprice - pred_x)^2)  # compute test error btwn actual & predicted salary
}
plot(validation_errors, type = "b")

for(i in 1:10) {
  coef_x <- coef(ld_frwd, id = i)                     # extract coefficients for model size i
  pred_x <- test_m[ , names(coef_x)] %*% coef_x           # predict salary using matrix algebra
  validation_errors[i] <- mean((test$Purprice - pred_x)^2)  # compute test error btwn actual & predicted salary
}
plot(validation_errors, type = "b")

for(i in 1:10) {
  coef_x <- coef(ld_bkwd, id = i)                     # extract coefficients for model size i
  pred_x <- test_m[ , names(coef_x)] %*% coef_x           # predict salary using matrix algebra
  validation_errors[i] <- mean((test$Purprice - pred_x)^2)  # compute test error btwn actual & predicted salary
}

# plot validation errors
plot(validation_errors, type = "b")

# ld_model <- lm(Purprice~FlorArea+BathTwo+CenHeat+Type,data = MyData)
# # ld_model <- lm(Purprice~FlorArea+BathTwo+CenHeat+Type+Easting+Bedrooms+Age,data = MyData)
# summary(ld_model)

predict.regsubsets <- function(object, newdata, id ,...) {
  form <- as.formula(object$call[[2]]) 
  mat <- model.matrix(form, newdata)
  coefi <- coef(object, id = id)
  xvars <- names(coefi)
  mat[, xvars] %*% coefi
}

k <- 10
set.seed(1)
folds <- sample(1:k, nrow(MyData), replace = TRUE)
cv_errors <- matrix(NA, k, 15, dimnames = list(NULL, paste(1:15)))

for(j in 1:k) {
  
  # perform best subset on rows not equal to j
  ld_model <- regsubsets(Purprice ~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, MyData[folds != j, ], nvmax = 15)
  
  # perform cross-validation
  for( i in 1:15) {
    pred_x <- predict.regsubsets(ld_model, MyData[folds == j, ], id = i)
    cv_errors[j, i] <- mean((MyData$Purprice[folds == j] - pred_x)^2)
    }
}

mean_cv_errors <- colMeans(cv_errors)

plot(mean_cv_errors, type = "b")

final_best <- regsubsets(Purprice ~Tenfree+CenHeat+BathTwo+NewPropD+FlorArea+ProfPct+Age+Type+Garage+Bedrooms, data = MyData , nvmax = 15)
coef(final_best, 15)
```

```{r}
MyData
```










